[package]
name = "boole"
version = "0.1.0"
edition = "2018"
description = "langjam submission"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
